name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: '请输入版本号'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Pack Translation Files
        run: |
          # 示例：假设你要把仓库根目录下的所有文件打包（排除 .github 文件夹）
          # .mcpack 本质上就是 zip 格式，所以直接用 zip 命令生成即可
          zip -r Bedrock.Translation.Patch.zip ./* -x ".github/*"
          cp Bedrock.Translation.Patch.zip Bedrock.Translation.Patch.mcpack
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version_name }}
          name: ${{ inputs.version_name }}
          body: |
            适用于Minecraft基岩版的简体中文译名修正资源包。

            <h2>更新日志</h2>

            - 更新至Beta/Preview ${{ inputs.version_name }}
            - 修复了若干项问题

            注：Beta/Preview版本的译文可能无法代表最终版本的质量。
          
          files: |
            Bedrock.Translation.Patch.mcpack
            Bedrock.Translation.Patch.zip
            
          draft: false
          prerelease: false
          fail_on_unmatched_files: true 
        env:
          GITHUB_TOKEN: 8e8ca0246849a18772cd08176ffd78ba0dbe85878b4d603fad22fc28a6241b1a35aed04a0984b1c2
