name: Manual Release

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      version_name:
        description: '26.40.30'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version_name }}
          name: ${{ inputs.version_name }}
          body: |
            An optimized version of Chinese Simplified translation for Minecraft Bedrock Edition

            <h2>Changelog</h2>

            - Update to BE Beta/Preview ${{ inputs.version_name }}
            - Several Fix

            Note: Beta builds are not the final product.
          
          files: |
            Bedrock.Translation.Patch.mcpack
            Bedrock.Translation.Patch.zip
            
          draft: false
          prerelease: false
          fail_on_unmatched_files: true 
        env:
          GITHUB_TOKEN: 8e8ca0246849a18772cd08176ffd78ba0dbe85878b4d603fad22fc28a6241b1a35aed04a0984b1c2
